### PR TITLE
Add info on compiling.

### PR DESCRIPTION
**Pull request by Derek1199**
Wanted to add info on compiling for this. So that everyone knows how to build this.

### CODE REVIEW

**Comment by SciresM** [comment]
Note: firmtool isn't required.

Also, for such a simple readme edit, please condense the many commits down into one, thank you!

**Comment by Derek1199** [comment]
okay. Let me fix it.

**Comment by Derek1199** [comment]
Okay. Did it. You can merge it now.

**Comment by Derek1199** [comment]
Why is this simple thing still open? It's easy to merge or decline.

**Comment by ThatNerdyPikachu** [comment]
lol

**Pull request closed without merging**
